databases:
  - name: micronaut
    databaseName: micronaut_bjkf
    user: micronaut_bjkf_user

services:
  - type: web
    name: Budget-app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: micronaut
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false